### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-audio-transformer-plugin-speechbrain-langdetect#4]
Configuration:

```json
  "lang": "fr-fr",
  "secondary_langs": [
    "en-us"
  ],

```

Error from listener:
```
Dec 07 10:05:15 rpi3b hivemind-voice-sat[894]: 2023-12-07 10:05:15.012 - HiveMind-voice-sat - ovos_dinkum_listener.transformers:transform:122 - DEBUG - checking audio transformer: <ovos_audio_transformer_plugin_speechbrain_langdetect.SpeechBrainLangClassifier object at 0x7ef2703340>
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]: UserWarning:
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]:     CategoricalEncoder.expect_len was never called: assuming category count of 45 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]: 2023-12-07 10:05:17.166 - HiveMind-voice-sat - ovos_dinkum_listener.transformers:transform:128 - ERROR - max() arg is an empty sequence
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]: Traceback (most recent call last):
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.9/site-packages/ovos_dinkum_listener/transformers.py", line 124, in transform
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]:     chunk, data = module.transform(chunk)
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.9/site-packages/ovos_audio_transformer_plugin_speechbrain_langdetect/__init__.py", line 62, in transform
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]:     lang, prob = max(probs, key=lambda k: k[1])
Dec 07 10:05:17 rpi3b hivemind-voice-sat[894]: ValueError: max() arg is an empty sequence

```

**Comment by JarbasAl** [comment]
fixed in https://github.com/OpenVoiceOS/ovos-audio-transformer-plugin-speechbrain-langdetect/commit/b916e768662a0ba2f0118bd55eaf911283d56865
